"use client";
import { useState, useMemo } from "react";
import { Search, User, MapPin, Users, IdCard } from "lucide-react";
import { User as UserType } from "./types/index";

const userData: UserType[] = [
  {
    srNo: 1,
    epicNo: "RSO8932188",
    partNo: "27/271/30",
    name: "Bhutekar Prizhar Santoshsing",
    relativeName: "Bhutekar Santoshsing",
    houseNo: "NA",
    address: "NA",
    age: 36,
    gender: "Male",
  },
  {
    srNo: 2,
    epicNo: "RSO8931875",
    partNo: "27/271/62",
    name: "Gole Mahendra Devidas",
    relativeName: "Gole Devidas",
    houseNo: "-",
    address: "-",
    age: 38,
    gender: "Male",
  },
  {
    srNo: 3,
    epicNo: "RSO9415175",
    partNo: "27/271/223",
    name: "Sabdkar Gofol Rameshwar",
    relativeName: "Sabdkar Rameshwar",
    houseNo: "-",
    address: "-",
    age: 24,
    gender: "Male",
  },
  {
    srNo: 4,
    epicNo: "KCC1076025",
    partNo: "27/271/520",
    name: "Bhatukar Keshav Sabkur",
    relativeName: "Bhatukar Sabkur",
    houseNo: "73",
    address: "73",
    age: 43,
    gender: "Male",
  },
  {
    srNo: 5,
    epicNo: "KCC1076264",
    partNo: "27/271/524",
    name: "Chalang Raju Kamalkishor",
    relativeName: "Chalang Kamalkishor",
    houseNo: "56",
    address: "56",
    age: 49,
    gender: "Male",
  },
  {
    srNo: 6,
    epicNo: "KCC1076272",
    partNo: "27/271/525",
    name: "Chalang Shival Raju",
    relativeName: "Chalang Raju",
    houseNo: "57",
    address: "57",
    age: 48,
    gender: "Female",
  },
  {
    srNo: 7,
    epicNo: "RSO9084393",
    partNo: "27/271/690",
    name: "Sabdkar Rameshwar Asharamji",
    relativeName: "Sabdkar Asharamji",
    houseNo: "258/5",
    address: "258/5",
    age: 58,
    gender: "Male",
  },
  {
    srNo: 8,
    epicNo: "RSO9084401",
    partNo: "27/271/691",
    name: "Sabdkar Rameshwar Rameshwar",
    relativeName: "Sabdkar Rameshwar",
    houseNo: "258/5",
    address: "258/5",
    age: 48,
    gender: "Female",
  },
  {
    srNo: 9,
    epicNo: "RSO9084377",
    partNo: "27/271/884",
    name: "Warkari Narayanrao Sudhaman",
    relativeName: "Warkari Sudhaman",
    houseNo: "262/5",
    address: "262/5",
    age: 56,
    gender: "Male",
  },
  {
    srNo: 10,
    epicNo: "RSO1416346",
    partNo: "27/271/885",
    name: "Warkari Bhagirathi Narayanrao",
    relativeName: "Warkari Narayanrao",
    houseNo: "262/5",
    address: "262/5",
    age: 71,
    gender: "Female",
  },
  {
    srNo: 11,
    epicNo: "RSO9084369",
    partNo: "27/271/886",
    name: "Warkari Govindrao Narayanrao",
    relativeName: "Warkari Narayanrao",
    houseNo: "262/5",
    address: "262/5",
    age: 62,
    gender: "Male",
  },
  {
    srNo: 12,
    epicNo: "RSO9084385",
    partNo: "27/271/887",
    name: "Warkari Pushpa Govindrao",
    relativeName: "Warkari Govindrao",
    houseNo: "262/5",
    address: "262/5",
    age: 39,
    gender: "Female",
  },
  {
    srNo: 13,
    epicNo: "RSO1416353",
    partNo: "27/271/888",
    name: "Warkari Vibhudatta Narayanrao",
    relativeName: "Warkari Narayanrao",
    houseNo: "262/5",
    address: "262/5",
    age: 42,
    gender: "Female",
  },
  {
    srNo: 14,
    epicNo: "RSO1533777",
    partNo: "27/271/1087",
    name: "Tharoke Anjali",
    relativeName: "Tharoke Shrikrishna",
    houseNo: "0",
    address: "0",
    age: 21,
    gender: "Female",
  },
  {
    srNo: 15,
    epicNo: "RSO1569532",
    partNo: "27/271/1093",
    name: "Sonke Prakashan",
    relativeName: "Sonke Chango",
    houseNo: "61",
    address: "61",
    age: 61,
    gender: "Male",
  },
  {
    srNo: 16,
    epicNo: "RSO1569540",
    partNo: "27/271/1094",
    name: "Sonke Ramesh",
    relativeName: "Sonke Abhinash",
    houseNo: "00",
    address: "00",
    age: 34,
    gender: "Female",
  },
  {
    srNo: 17,
    epicNo: "RSO1569557",
    partNo: "27/271/1095",
    name: "Sonke Anil",
    relativeName: "Sonke Prakashan",
    houseNo: "0",
    address: "0",
    age: 40,
    gender: "Male",
  },
  {
    srNo: 18,
    epicNo: "RSO1608223",
    partNo: "27/271/1113",
    name: "Ogalekar Nilesh Sureshkanta",
    relativeName: "Ogalekar Sureshkanta",
    houseNo: "06",
    address: "06",
    age: 33,
    gender: "Male",
  },
  {
    srNo: 19,
    epicNo: "RSO1533835",
    partNo: "27/271/1142",
    name: "Sangal Pankaj",
    relativeName: "Sangal Raju",
    houseNo: "67",
    address: "67",
    age: 43,
    gender: "Male",
  },
  {
    srNo: 20,
    epicNo: "RSO1533827",
    partNo: "27/271/1143",
    name: "Gunde Milind",
    relativeName: "Gunde Laxman",
    houseNo: "75",
    address: "75",
    age: 54,
    gender: "Male",
  },
  {
    srNo: 21,
    epicNo: "RSO1585108",
    partNo: "27/271/1144",
    name: "Gunde Amit",
    relativeName: "Gunde Laxman",
    houseNo: "52",
    address: "52",
    age: 23,
    gender: "Female",
  },
  {
    srNo: 22,
    epicNo: "RSO1585090",
    partNo: "27/271/1145",
    name: "Gunde Ankita",
    relativeName: "Gunde Laxman",
    houseNo: "52",
    address: "52",
    age: 20,
    gender: "Female",
  },
  {
    srNo: 23,
    epicNo: "RSO1635317",
    partNo: "27/271/1226",
    name: "Shinde Avinash Prabhakar",
    relativeName: "Shinde Raghunath Chango",
    houseNo: "G9-Krishn Nagar Tek",
    address: "G9-Krishn Nagar Tek",
    age: 23,
    gender: "Female",
  },
  {
    srNo: 24,
    epicNo: "RSO1801042",
    partNo: "27/271/1343",
    name: "Tayde Somesh Niluti",
    relativeName: "Tayde Niluti Vitthal",
    houseNo: "Jagdamba Nagar",
    address: "Jagdamba Nagar",
    age: 18,
    gender: "Male",
  },
  {
    srNo: 25,
    epicNo: "RSO1890706",
    partNo: "27/271/1410",
    name: "Kuduve Divya Kishor",
    relativeName: "Kuduve Kishor Devidas",
    houseNo: "22",
    address: "Vyankatesh Nagar",
    age: 22,
    gender: "Female",
  },
  {
    srNo: 26,
    epicNo: "RSO1893445",
    partNo: "27/271/1414",
    name: "Malaskar Sanju Bai Ramwati",
    relativeName: "Malaskar Ramwati",
    houseNo: "53",
    address: "Tehsil Karyalay Parisar",
    age: 53,
    gender: "Female",
  },
  {
    srNo: 27,
    epicNo: "RSO1494822",
    partNo: "27/272/674",
    name: "Mohammad Iftikhar Naseha Parveen",
    relativeName: "Mohammad Iftikhar Mohammad Iftik",
    address: "",
    houseNo: "PP PATIL NAGAR",
    age: 30,
    gender: "Female",
    status: "Active",
    lastUpdated: "2025-11-24",
  },
  {
    srNo: 28,
    epicNo: "RSO1494814",
    partNo: "27/272/675",
    name: "Saba Naz Mohammad Tariq",
    relativeName: "Mohammad Tariq",
    address: "",
    houseNo: "PP PATIL NAGAR",
    age: 29,
    gender: "Female",
    status: "Active",
    lastUpdated: "2025-11-24",
  },
  {
    srNo: 29,
    epicNo: "RSO1586502",
    partNo: "27/272/693",
    name: "Mete Megha Manish",
    relativeName: "Mete Manish Vijayrao",
    address: "",
    houseNo: "1",
    age: 37,
    gender: "Female",
    status: "Active",
    lastUpdated: "2025-11-24",
  },
  {
    srNo: 30,
    epicNo: "KCC1064583",
    partNo: "27/272/828",
    name: "Tayde Kailas Kisan",
    relativeName: "Tayde Kisan",
    address: "",
    houseNo: "74",
    age: 50,
    gender: "Male",
    status: "Active",
    lastUpdated: "2025-11-24",
  },
  {
    srNo: 31,
    epicNo: "RSO6270185",
    partNo: "27/272/829",
    name: "Tayde Varshatai Kailas",
    relativeName: "Tayde Kailas",
    address: "",
    houseNo: "74",
    age: 40,
    gender: "Female",
    status: "Active",
    lastUpdated: "2025-11-24",
  },
  {
    srNo: 32,
    epicNo: "RSO7506421",
    partNo: "27/272/865",
    name: "Bharti Rishikesh Surendra",
    relativeName: "Bharti Surendra",
    address: "",
    houseNo: "180",
    age: 27,
    gender: "Male",
    status: "Active",
    lastUpdated: "2025-11-24",
  },
  {
    srNo: 33,
    epicNo: "RSO9846288",
    partNo: "27/272/866",
    name: "Bharti Surendra Vinayak",
    relativeName: "Bharti Vinayak",
    address: "",
    houseNo: "180",
    age: 72,
    gender: "Male",
    status: "Active",
    lastUpdated: "2025-11-24",
  },
  {
    srNo: 34,
    epicNo: "KCC1096429",
    partNo: "27/272/867",
    name: "Bharti Shobhaj Surendra",
    relativeName: "Bharti Surendra",
    address: "",
    houseNo: "180",
    age: 62,
    gender: "Female",
    status: "Active",
    lastUpdated: "2025-11-24",
  },
  {
    srNo: 35,
    epicNo: "KCC1098334",
    partNo: "27/272/868",
    name: "Uchade Hargabai Mahadev",
    relativeName: "Uchade Mahadev",
    address: "",
    houseNo: "1800",
    age: 77,
    gender: "Female",
    status: "Active",
    lastUpdated: "2025-11-24",
  },
  {
    srNo: 36,
    epicNo: "KCC1096460",
    partNo: "27/272/869",
    name: "Uchade Sunil Mahadev",
    relativeName: "Uchade Mahadev",
    address: "",
    houseNo: "1803",
    age: 52,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 37,
    epicNo: "KCC1098342",
    partNo: "27/272/870",
    name: "Uchade Jyoti Sunil",
    relativeName: "Uchade Sunil",
    address: "",
    houseNo: "1803",
    age: 44,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 38,
    epicNo: "KCC1096080",
    partNo: "27/272/871",
    name: "Rafikun Nisa Sattar",
    relativeName: "Sattar",
    address: "",
    houseNo: "181",
    age: 88,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 39,
    epicNo: "KCC1097997",
    partNo: "27/272/872",
    name: "Asliq A Sattar",
    relativeName: "A Sattar",
    address: "",
    houseNo: "181",
    age: 51,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 40,
    epicNo: "KCC1098003",
    partNo: "27/272/873",
    name: "Asm Parveen A Salik",
    relativeName: "A Salik",
    address: "",
    houseNo: "181",
    age: 49,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 41,
    epicNo: "KCC1107630",
    partNo: "27/272/874",
    name: "Tarannum Shafaq A Sattar",
    relativeName: "Shafaq A Sattar",
    address: "",
    houseNo: "181",
    age: 47,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 42,
    epicNo: "KCC1096098",
    partNo: "27/272/875",
    name: "Sattar Abdul Sattar Sheikh Badu",
    relativeName: "Sattar Sheikh Badu",
    address: "",
    houseNo: "182",
    age: 98,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 43,
    epicNo: "RSO9846304",
    partNo: "27/272/876",
    name: "Mahmood Ali Jainobanoz Ali",
    relativeName: "Mahmood Ali Ali",
    address: "",
    houseNo: "181",
    age: 85,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 44,
    epicNo: "KCC1097880",
    partNo: "27/272/877",
    name: "A Shakeel A Salam",
    relativeName: "Shakeel A Salam",
    address: "",
    houseNo: "183",
    age: 43,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 45,
    epicNo: "KCC1075779",
    partNo: "27/272/879",
    name: "Shaguftabanoz Salam",
    relativeName: "Salam",
    address: "",
    houseNo: "183",
    age: 79,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 46,
    epicNo: "RSO9846320",
    partNo: "27/272/878",
    name: "Rajgure Parvati Vishwanath",
    relativeName: "Rajgure Vishwanath",
    address: "",
    houseNo: "183",
    age: 52,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },

  {
    srNo: 47,
    epicNo: "RSO7024698",
    partNo: "27/272/880",
    name: "Rajgure Rajesh Vishwanath",
    relativeName: "Rajgure Vishwanath",
    address: "",
    houseNo: "183",
    age: 41,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 48,
    epicNo: "RSO9846312",
    partNo: "27/272/881",
    name: "Salam A Salam Aziz",
    relativeName: "Salam Aziz",
    address: "",
    houseNo: "1830",
    age: 63,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 49,
    epicNo: "RSO7168826",
    partNo: "27/272/882",
    name: "Sheikh Abdul Kafeel Abdul Salam",
    relativeName: "Sheikh Abdul Salam",
    address: "",
    houseNo: "183",
    age: 37,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 50,
    epicNo: "KCC1076009",
    partNo: "27/272/883",
    name: "Syed Ashraf Sheikh Kasam",
    relativeName: "Ashraf Sheikh Kasam",
    address: "",
    houseNo: "1830",
    age: 77,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 51,
    epicNo: "RSO1446343",
    partNo: "27/272/884",
    name: "Sai Irfan Sheikh Ashraf",
    relativeName: "Sheikh Ashraf",
    address: "",
    houseNo: "1830",
    age: 48,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 52,
    epicNo: "KCC1076181",
    partNo: "27/272/885",
    name: "Talokar Vandana Vinayak",
    relativeName: "Talokar Vinayak",
    address: "",
    houseNo: "1830",
    age: 62,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 53,
    epicNo: "RSO7024706",
    partNo: "27/272/886",
    name: "Tale Sahebrao Janrao",
    relativeName: "Tale Janrao",
    address: "",
    houseNo: "184",
    age: 63,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 54,
    epicNo: "RSO9084591",
    partNo: "27/272/887",
    name: "Talokar Vinayak Bhagwan",
    relativeName: "Talokar Bhagwan",
    address: "",
    houseNo: "185",
    age: 63,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 55,
    epicNo: "RSO9846346",
    partNo: "27/272/888",
    name: "Talokar Vandana Vinayak",
    relativeName: "Talokar Vinayak",
    address: "",
    houseNo: "185",
    age: 58,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 56,
    epicNo: "RSO1435577",
    partNo: "27/272/889",
    name: "Mohammad Haroon",
    relativeName: "Noor Mohammad Suleman",
    address: "",
    houseNo: "1850",
    age: 80,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 57,
    epicNo: "KCC1108224",
    partNo: "27/272/899",
    name: "Mohammad Aslam Mohammad Haroon",
    relativeName: "Mohammad Haroon",
    address: "",
    houseNo: "1860",
    age: 55,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 58,
    epicNo: "RSO1423524",
    partNo: "27/272/900",
    name: "Asma Bano Mohammad Aslam",
    relativeName: "Moh Aslam",
    address: "",
    houseNo: "1860",
    age: 49,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 59,
    epicNo: "KCC1097955",
    partNo: "27/272/901",
    name: "Mohammad Amin Mohammad Haroon",
    relativeName: "Mohammad Haroon",
    address: "",
    houseNo: "1860",
    age: 42,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 60,
    epicNo: "RSO7024854",
    partNo: "27/272/902",
    name: "Mo Shoaib Mo Iqbal",
    relativeName: "Mo Iqbal",
    address: "",
    houseNo: "02",
    age: 45,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 61,
    epicNo: "RSO7167463",
    partNo: "27/272/903",
    name: "Rubina Masira Mo Shoaib",
    relativeName: "Mo Shoaib",
    address: "",
    houseNo: "186",
    age: 39,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 62,
    epicNo: "KCC1096437",
    partNo: "27/272/904",
    name: "Umarkar Nirmala Jagdev",
    relativeName: "Umarkar Jagdev",
    address: "",
    houseNo: "186d",
    age: 65,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 63,
    epicNo: "KCC1107085",
    partNo: "27/272/905",
    name: "Umarkar Kailas Jagdev",
    relativeName: "Umarkar Jagdev",
    address: "",
    houseNo: "1860",
    age: 47,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 64,
    epicNo: "KCC1096395",
    partNo: "27/272/906",
    name: "Umarkar Vilas Jagdev",
    relativeName: "Umarkar Jagdev",
    address: "",
    houseNo: "1860",
    age: 42,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 65,
    epicNo: "KCC1097310",
    partNo: "27/272/907",
    name: "Khatri Sunil Mohan",
    relativeName: "Khatri Mohan",
    address: "",
    houseNo: "186k",
    age: 52,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 66,
    epicNo: "KCC1097971",
    partNo: "27/272/908",
    name: "Khatri Manoj Mohan",
    relativeName: "Khatri Mohan",
    address: "",
    houseNo: "1865",
    age: 50,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 67,
    epicNo: "RSO7024847",
    partNo: "27/272/909",
    name: "Khatri Kavita Sunil",
    relativeName: "Khatri Sunil",
    address: "",
    houseNo: "186k",
    age: 46,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 68,
    epicNo: "KCC1097963",
    partNo: "27/272/910",
    name: "Khatri Rinku Manoj",
    relativeName: "Khatri Manoj",
    address: "",
    houseNo: "186k",
    age: 44,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 69,
    epicNo: "KCC1076595",
    partNo: "27/272/911",
    name: "Mundhe Asha Lahuji",
    relativeName: "Mundhe Lahuji",
    address: "",
    houseNo: "188",
    age: 42,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 70,
    epicNo: "RSO9846411",
    partNo: "27/272/912",
    name: "Mundhe Shriram Ravji",
    relativeName: "Mundhe Ravji",
    address: "",
    houseNo: "188",
    age: 74,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 71,
    epicNo: "RSO9846429",
    partNo: "27/272/913",
    name: "Mundhe Kasturabai Shriram",
    relativeName: "Mundhe Shriram",
    address: "",
    houseNo: "188",
    age: 72,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 72,
    epicNo: "RSO9846437",
    partNo: "27/272/914",
    name: "Mundhe Lahu Shriram",
    relativeName: "Mundhe Shriram",
    address: "",
    houseNo: "188",
    age: 50,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 73,
    epicNo: "RSO7534225",
    partNo: "27/272/915",
    name: "Shaikh Salim",
    relativeName: "Shaikh Ibrahim",
    address: "",
    houseNo: "188",
    age: 34,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 74,
    epicNo: "RSO9846452",
    partNo: "27/272/916",
    name: "Battulwar Laxmi Mallanna",
    relativeName: "Battulwar Mallanna",
    address: "",
    houseNo: "189",
    age: 87,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 75,
    epicNo: "RSO9846460",
    partNo: "27/272/917",
    name: "Battulwar Gangaram Mallanna",
    relativeName: "Battulwar Mallanna",
    address: "",
    houseNo: "189",
    age: 55,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 76,
    epicNo: "KCC1096007",
    partNo: "27/272/918",
    name: "Battulwar Ghanshyam Mallanna",
    relativeName: "Battulwar Mallanna",
    address: "",
    houseNo: "189",
    age: 55,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 77,
    epicNo: "RSO1495837",
    partNo: "27/272/919",
    name: "Battulwar Santosh Mallanna",
    relativeName: "Battulwar Mallanna",
    address: "",
    houseNo: "189",
    age: 47,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 78,
    epicNo: "KCC1096015",
    partNo: "27/272/920",
    name: "Battulwar Mangala Ghanshyam",
    relativeName: "Battulwar Ghanshyam",
    address: "",
    houseNo: "189",
    age: 43,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 79,
    epicNo: "KCC1096023",
    partNo: "27/272/921",
    name: "Battulwar Jyoti Gangaram",
    relativeName: "Battulwar Gangaram",
    address: "",
    houseNo: "189",
    age: 42,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 80,
    epicNo: "RSO7534217",
    partNo: "27/272/922",
    name: "Shaikh Ramratabi Shaikh Salim",
    relativeName: "Shaikh Salim",
    address: "",
    houseNo: "189",
    age: 28,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 81,
    epicNo: "RSO7168883",
    partNo: "27/272/923",
    name: "Kusumbe Shivdas Devidas",
    relativeName: "Kusumbe Devidas",
    address: "",
    houseNo: "190",
    age: 30,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 82,
    epicNo: "RSO9667536",
    partNo: "27/272/924",
    name: "Dandge Rameshwar",
    relativeName: "Dandge Janardan",
    address: "",
    houseNo: "191",
    age: 45,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 83,
    epicNo: "RSO7168867",
    partNo: "27/272/949",
    name: "Thakur Dineshsingh Ganeshsingh",
    relativeName: "Thakur Ganeshsingh",
    address: "",
    houseNo: "852",
    age: 33,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 84,
    epicNo: "RSO7168875",
    partNo: "27/272/950",
    name: "Thakur Nareshsingh Ganeshsingh",
    relativeName: "Thakur Ganeshsingh",
    address: "",
    houseNo: "852",
    age: 31,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 85,
    epicNo: "RSO7455652",
    partNo: "27/272/951",
    name: "Chincholkar Jyoti Prakash",
    relativeName: "Chincholkar Prakash",
    address: "",
    houseNo: "1060",
    age: 40,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 86,
    epicNo: "RSO7168859",
    partNo: "27/272/952",
    name: "Mali Aniruddha Punjabrao",
    relativeName: "Mali Punjabrao",
    address: "",
    houseNo: "1068",
    age: 29,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 87,
    epicNo: "RSO9583550",
    partNo: "27/272/953",
    name: "Mohammad Wasim",
    relativeName: "Sheikh Salim",
    address: "",
    houseNo: "1127",
    age: 24,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 88,
    epicNo: "RSO7455702",
    partNo: "27/272/954",
    name: "Chincholekar Prakash Murlidharrao",
    relativeName: "Chincholekar Murlidharrao",
    address: "",
    houseNo: "1160",
    age: 50,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 89,
    epicNo: "RSO7455694",
    partNo: "27/272/955",
    name: "Raut Surekha Anant",
    relativeName: "Raut Anant",
    address: "",
    houseNo: "1161",
    age: 55,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 90,
    epicNo: "RSO7455686",
    partNo: "27/272/956",
    name: "Raut Rishabh Anant",
    relativeName: "Raut Anant",
    address: "",
    houseNo: "1161",
    age: 27,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 91,
    epicNo: "RSO9584954",
    partNo: "27/272/957",
    name: "Asiya Parveen Shoaib Khan",
    relativeName: "Shoaib Khan Haider Khan",
    address: "",
    houseNo: "1216",
    age: 26,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 92,
    epicNo: "RSO9584947",
    partNo: "27/272/958",
    name: "Sheikh Aqeel",
    relativeName: "Sheikh Anees",
    address: "",
    houseNo: "1217",
    age: 22,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 93,
    epicNo: "RSO9583543",
    partNo: "27/272/959",
    name: "Anisa Abdul Gaffar",
    relativeName: "Abdul Gaffar",
    address: "",
    houseNo: "1218",
    age: 31,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 94,
    epicNo: "RSO1509827",
    partNo: "27/272/961",
    name: "Shine Bee Samad Khan",
    relativeName: "Samad Khan Abdullah Khan",
    address: "",
    houseNo: "140/1",
    age: 33,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 95,
    epicNo: "MRN1780725",
    partNo: "27/272/962",
    name: "Tayade Ambadas",
    relativeName: "Tayade Amol",
    address: "",
    houseNo: "1754",
    age: 68,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 96,
    epicNo: "MRN1780733",
    partNo: "27/272/963",
    name: "Tayade Savita Ambadas",
    relativeName: "Tayade Ambadas",
    address: "",
    houseNo: "1754",
    age: 59,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 97,
    epicNo: "KCC1107200",
    partNo: "27/272/964",
    name: "Bharti Vilas Shankar",
    relativeName: "Bharti Shankar",
    address: "",
    houseNo: "1853",
    age: 54,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 98,
    epicNo: "KCC1107036",
    partNo: "27/272/965",
    name: "Daberav Mangala Sitaram",
    relativeName: "Daberav Sitaram",
    address: "",
    houseNo: "1853",
    age: 45,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 99,
    epicNo: "KCC1098789",
    partNo: "27/272/966",
    name: "Morkhade Nitin Shrikrishna",
    relativeName: "Morkhade Shrikrishna",
    address: "",
    houseNo: "1854",
    age: 53,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 100,
    epicNo: "KCC1098797",
    partNo: "27/272/967",
    name: "Morkhade Shalini Nitin",
    relativeName: "Morkhade Nitin",
    address: "",
    houseNo: "1854",
    age: 48,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 101,
    epicNo: "RSO1592120",
    partNo: "27/272/968",
    name: "Morkhade Abhishek",
    relativeName: "Morkhade Nitin",
    address: "",
    houseNo: "1854",
    age: 23,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 102,
    epicNo: "RSO3514346",
    partNo: "27/272/969",
    name: "Morkhade Ashok Vishwanath",
    relativeName: "Morkhade Vishwanath",
    address: "",
    houseNo: "1855",
    age: 67,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 103,
    epicNo: "RSO3514353",
    partNo: "27/272/970",
    name: "Morkhade Vandana Ashok",
    relativeName: "Morkhade Ashok",
    address: "",
    houseNo: "1855",
    age: 59,
    gender: "Female",
    status: "Active",
    lastUpdated: "",
  },
  {
    srNo: 104,
    epicNo: "KCC1098870",
    partNo: "27/272/971",
    name: "Nandane Siddhesh Vasant",
    relativeName: "Nandane Vasant",
    address: "",
    houseNo: "1856",
    age: 45,
    gender: "Male",
    status: "Active",
    lastUpdated: "",
  },
  {
    "srNo": 105,
    "epicNo": "RSO9085820",
    "partNo": "27/272/972",
    "name": "Madhare Ganesh",
    "relativeName": "Madhare Namdev",
    "address": "",
    "houseNo": "185-6",
    "age": 41,
    "gender": "Male",
    "status": "Active",
    "lastUpdated": ""
  },
  {
    "srNo": 106,
    "epicNo": "KCC1076389",
    "partNo": "27/272/973",
    "name": "Mali Rekha Punjabrao",
    "relativeName": "Mali Punjabrao",
    "address": "",
    "houseNo": "1857",
    "age": 57,
    "gender": "Female",
    "status": "Active",
    "lastUpdated": ""
  },
  {
    "srNo": 107,
    "epicNo": "KCC1098664",
    "partNo": "27/272/974",
    "name": "Mankar Gayabai Namdev",
    "relativeName": "Mankar Namdev",
    "address": "",
    "houseNo": "1858",
    "age": 74,
    "gender": "Female",
    "status": "Active",
    "lastUpdated": ""
  },
  {
    "srNo": 108,
    "epicNo": "KCC1107135",
    "partNo": "27/272/975",
    "name": "Pahurkar Dadarav Tulshiram",
    "relativeName": "Pahurkar Tulshiram",
    "address": "",
    "houseNo": "1892",
    "age": 63,
    "gender": "Male",
    "status": "Active",
    "lastUpdated": ""
  },
  {
    "srNo": 109,
    "epicNo": "KCC1107143",
    "partNo": "27/272/976",
    "name": "Pahurkar Padmavati Dadarav",
    "relativeName": "Pahurkar Dadarav",
    "address": "",
    "houseNo": "1892",
    "age": 57,
    "gender": "Female",
    "status": "Active",
    "lastUpdated": ""
  },
  {
    "srNo": 110,
    "epicNo": "KCC1107044",
    "partNo": "27/272/977",
    "name": "Kusumbe Devidas Sakharam",
    "relativeName": "Kusumbe Sakharam",
    "address": "",
    "houseNo": "1904",
    "age": 55,
    "gender": "Male",
    "status": "Active",
    "lastUpdated": ""
  },
  {
    "srNo": 111,
    "epicNo": "KCC1098219",
    "partNo": "27/272/979",
    "name": "Kusumbe Rukhma Devidas",
    "relativeName": "Kusumbe Devidas",
    "address": "",
    "houseNo": "1905",
    "age": 55,
    "gender": "Female",
    "status": "Active",
    "lastUpdated": ""
  },
  {
    "srNo": 112,
    "epicNo": "KCC1098060",
    "partNo": "27/272/980",
    "name": "Wankhede Manakarna Haribhau",
    "relativeName": "Wankhede Haribhau",
    "address": "",
    "houseNo": "1909",
    "age": 70,
    "gender": "Male",
    "status": "Active",
    "lastUpdated": ""
  },
  {
    "srNo": 113,
    "epicNo": "KCC1098078",
    "partNo": "27/272/981",
    "name": "Wankhede Gautam Haribhau",
    "relativeName": "Wankhede Haribhau",
    "address": "",
    "houseNo": "1909A",
    "age": 57,
    "gender": "Male",
    "status": "Active",
    "lastUpdated": ""
  },
  {
    "srNo": 114,
    "epicNo": "RSO1527878",
    "partNo": "27/272/982",
    "name": "Wankhede Pushplata Gautam",
    "relativeName": "Wankhede Gautam",
    "address": "",
    "houseNo": "1909A",
    "age": 52,
    "gender": "Female",
    "status": "Active",
    "lastUpdated": ""
  },
  {
    "srNo": 115,
    "epicNo": "RSO9667494",
    "partNo": "27/272/983",
    "name": "Wankhade Gaurav",
    "relativeName": "Wankhade Gautam",
    "address": "",
    "houseNo": "190-9",
    "age": 24,
    "gender": "Male",
    "status": "Active",
    "lastUpdated": ""
  },
  {
    "srNo": 116,
    "epicNo": "RS09667494",
    "partNo": "27/272/983",
    "name": "Dandage Parmeshwar",
    "relativeName": "Dandage Janardan",
    "address": "",
    "houseNo": "191/1",
    "age": 42,
    "gender": "Male",
    "status": "Active",
    "lastUpdated": ""
  }

];

const genderColors: Record<string, string> = {
  Male: "bg-blue-100 text-blue-800",
  Female: "bg-pink-100 text-pink-800",
  "Not Stated": "bg-gray-100 text-gray-800",
};

export default function UserManagement() {
  const [searchTerm, setSearchTerm] = useState<string>("");

  const filteredUsers = useMemo((): UserType[] => {
    if (!searchTerm) return userData;

    const lowercasedSearch = searchTerm.toLowerCase();
    return userData.filter(
      (user) =>
        user?.name?.toLowerCase().includes(lowercasedSearch) ||
        user?.epicNo?.toLowerCase().includes(lowercasedSearch) ||
        user?.partNo?.toLowerCase().includes(lowercasedSearch) ||
        user?.relativeName?.toLowerCase().includes(lowercasedSearch) ||
        user?.address?.toLowerCase().includes(lowercasedSearch)
    );
  }, [searchTerm]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50 py-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            User Management
          </h1>
          <p className="text-gray-600">Search and view user records</p>
        </div>

        {/* Search Bar */}
        <div className="mb-8">
          <div className="relative max-w-2xl mx-auto">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <Search className="h-5 w-5 text-gray-400" />
            </div>
            <input
              type="text"
              className="block w-full pl-10 pr-4 py-3 border border-gray-300 rounded-xl bg-white text-black shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200"
              placeholder="Search users by name, EPIC number, address, husban name..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
        </div>

        {/* Results Count */}
        <div className="mb-6">
          <p className="text-sm text-gray-600">
            {filteredUsers.length} user{filteredUsers.length !== 1 ? "s" : ""}{" "}
            found
            {searchTerm && ` for "${searchTerm}"`}
          </p>
        </div>

        {/* Users Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
          {filteredUsers.map((user) => (
            <div
              key={user.srNo}
              className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6 hover:shadow-lg transition-all duration-300"
            >
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center space-x-3">
                  <div
                    className={`p-2 rounded-xl ${genderColors[user.gender]}`}
                  >
                    <User className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-gray-900 line-clamp-1">
                      {user.name}
                    </h3>
                    <p className="text-sm text-gray-500">EPIC: {user.epicNo}</p>
                  </div>
                </div>
                <div className="flex flex-col items-end space-y-2">
                  <span
                    className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                      genderColors[user.gender]
                    }`}
                  >
                    {user.gender}
                  </span>
                  <span
                    className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                      genderColors[user.gender]
                    }`}
                  >
                    {user.srNo}
                  </span>
                </div>
              </div>

              <div className="space-y-3">
                <div className="flex items-center text-sm text-gray-600">
                  <IdCard className="h-4 w-4 mr-2 flex-shrink-0" />
                  <span className="line-clamp-1">Part: {user.partNo}</span>
                </div>

                {user.relativeName && (
                  <div className="flex items-center text-sm text-gray-600">
                    <Users className="h-4 w-4 mr-2 flex-shrink-0" />
                    <span className="line-clamp-1">{user.relativeName}</span>
                  </div>
                )}

                <div className="flex items-center text-sm text-gray-600">
                  <MapPin className="h-4 w-4 mr-2 flex-shrink-0" />
                  <span className="line-clamp-1">
                    {user.address || "Address not specified"}
                  </span>
                </div>

                <div className="flex items-center justify-between text-xs text-gray-500 pt-2 border-t border-gray-100">
                  <span>Age: {user.age || "N/A"}</span>
                  <span>House No: {user.houseNo}</span>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* No Results */}
        {filteredUsers.length === 0 && (
          <div className="text-center py-16">
            <div className="bg-white rounded-2xl p-12 border border-gray-200">
              <User className="mx-auto h-16 w-16 text-gray-300 mb-4" />
              <h3 className="text-lg font-semibold text-gray-900 mb-2">
                No users found
              </h3>
              <p className="text-gray-600 mb-6 max-w-md mx-auto">
                {searchTerm
                  ? `No results found for "${searchTerm}". Try adjusting your search terms.`
                  : "No users available."}
              </p>
              {searchTerm && (
                <button
                  onClick={() => setSearchTerm("")}
                  className="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition-colors duration-200"
                >
                  Clear search
                </button>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
